apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: robo3t
  generation: 1
  labels:
    app: robo3t
  name: robo3t
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: robo3t
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: robo3t
    spec:
      containers:
      - env:
        - name: DISPLAY_WIDTH
          value: "2880"
        - name: DISPLAY_HEIGHT
          value: "1620"
        image: jlti/robo3t-docker:v0.3
        imagePullPolicy: IfNotPresent
        name: robo3t
        ports:
        - containerPort: 5800
          protocol: TCP
        - containerPort: 5900
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 500Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: robo3t
  name: robo3t
  namespace: default
spec:
  ports:
  - name: http
    port: 5800
    protocol: TCP
    targetPort: 5800
  - name: vnc
    port: 5900
    protocol: TCP
    targetPort: 5900
  selector:
    app: robo3t
  sessionAffinity: None
  type: ClusterIP

